name: mr_orange_store
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.5 <4.0.0'
#-------------- PACKAGES --------------#
dependencies:
  flutter:
    sdk: flutter
   #Icons
  cupertino_icons: ^1.0.2
  #State Management
  get: ^4.6.6
  #Icons
  iconsax: ^0.0.8
  http: ^1.1.0
  url_launcher: ^6.2.4
  intl: ^0.19.0
  firebase_storage: ^11.6.0
  connectivity_plus: ^5.0.2
  lottie: ^2.7.0
  get_storage: ^2.1.1
  logger: ^2.5.0
  flutter_native_splash: ^2.3.7
  smooth_page_indicator: ^1.2.1
  carousel_slider: ^5.1.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
#-------------- ./PACKAGES END --------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800