// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVm6BB9_Dk9LYIngrjNS4GZNOKbtcK8OM',
    appId: '1:317289061297:android:88fe5129608b9e9b68fb90',
    messagingSenderId: '317289061297',
    projectId: 'mr-orange-store-7bea4',
    storageBucket: 'mr-orange-store-7bea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl4wAtLG-_zeR4ctdmkBMPKFHY985sXcY',
    appId: '1:317289061297:ios:226d02f6448432aa68fb90',
    messagingSenderId: '317289061297',
    projectId: 'mr-orange-store-7bea4',
    storageBucket: 'mr-orange-store-7bea4.firebasestorage.app',
    androidClientId: '317289061297-jr6frnuibhki9v2o03mh5biptdmbk6c3.apps.googleusercontent.com',
    iosClientId: '317289061297-1vblp1kmjjtipqrbho6his2suk5kfv5u.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrOrangeStore',
  );

}